name: Run Tests

on:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Make script executable
        run: chmod +x pipeline.sh

      - name: Run test pipeline
        run: ./pipeline.sh
